<a href="https://colab.research.google.com/github/IrakizaGaius/LiveCodingSession/blob/main/Live_coding_Neuron_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Write a class Neuron that defines a single neuron performing binary classification:

class constructor: def __init__(self, nx):
nx is the number of input features to the neuron
If nx is not an integer, raise a TypeError with the exception: nx must be an integer
If nx is less than 1, raise a ValueError with the exception: nx must be a positive integer
All exceptions should be raised in the order listed above
Public instance attributes:
W: The weights vector for the neuron. Upon instantiation, it should be initialized using a random normal distribution.
b: The bias for the neuron. Upon instantiation, it should be initialized to 0.
A: The activated output of the neuron (prediction). Upon instantiation, it should be initialized to 0.

In [64]:
import pandas as pd
import numpy as np

In [65]:
data = pd.read_csv('https://gist.githubusercontent.com/armgilles/194bcff35001e7eb53a2a8b441e8b2c6/raw/92200bc0a673d5ce2110aaad4544ed6c4010f687/pokemon.csv')

data.head(5)


#                   Name Type 1  Type 2  Total  HP  Attack  Defense  \
0  1              Bulbasaur  Grass  Poison    318  45      49       49   
1  2                Ivysaur  Grass  Poison    405  60      62       63   
2  3               Venusaur  Grass  Poison    525  80      82       83   
3  3  VenusaurMega Venusaur  Grass  Poison    625  80     100      123   
4  4             Charmander   Fire     NaN    309  39      52       43   

   Sp. Atk  Sp. Def  Speed  Generation  Legendary  
0       65       65     45           1      False  
1       80       80     60           1      False  
2      100      100     80           1      False  
3      122      120     80           1      False  
4       60       50     65           1      False

In [66]:
#data.info()
new_data = pd.get_dummies(data)
new_data.head(5)

#  Total  HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  Generation  \
0  1    318  45      49       49       65       65     45           1   
1  2    405  60      62       63       80       80     60           1   
2  3    525  80      82       83      100      100     80           1   
3  3    625  80     100      123      122      120     80           1   
4  4    309  39      52       43       60       50     65           1   

   Legendary  ...  Type 2_Ghost  Type 2_Grass  Type 2_Ground  Type 2_Ice  \
0      False  ...         False         False          False       False   
1      False  ...         False         False          False       False   
2      False  ...         False         False          False       False   
3      False  ...         False         False          False       False   
4      False  ...         False         False          False       False   

   Type 2_Normal  Type 2_Poison  Type 2_Psychic  Type 2_Rock  Type 2_Steel  \
0          False           True           False        False         False   
1          False           True           False        False         False   
2          False           True           False        False         False   
3          False           True           False        False         False   
4          False          False           False        False         False   

   Type 2_Water  
0         False  
1         False  
2         False  
3         False  
4         False  

[5 rows x 846 columns]

In [67]:
input = new_data.drop(['Legendary'], axis = 1)
input = input.astype(float).to_numpy()
print(input)

[[  1. 318.  45. ...   0.   0.   0.]
 [  2. 405.  60. ...   0.   0.   0.]
 [  3. 525.  80. ...   0.   0.   0.]
 ...
 [720. 600.  80. ...   0.   0.   0.]
 [720. 680.  80. ...   0.   0.   0.]
 [721. 600.  80. ...   0.   0.   1.]]


In [68]:
print(input.shape)
print(input.dtype)

(800, 845)
float64


In [69]:
nx = input.shape[1]

In [77]:
class constructor:
  def __init__(self, nx):
        if not isinstance(nx, int):
            raise TypeError("nx must be an integer")
        if nx < 1:
            raise ValueError("nx must be a positive integer")

        self.W = np.random.randn(1, nx)
        self.b = 0.0
        self.A = 0

  def forward_prop(self, X):
        z = np.dot(self.W, X) + self.b
        self.A = 1 / (1 + np.exp(-z))
        return self.A

try:
    X = input.reshape((input.shape[0], -1)).T
    n_features = X.shape[0]
    neuron = constructor(n_features)

    # Forward propagation
    A = neuron.forward_prop(X)

    # Print the output
    print("Activated output (A):")
    print(A)

except NameError:
    print("Error: The 'input' variable is not defined. Please provide the input data as a NumPy array.")
except Exception as e:
    print(f"An error occurred: {e}")

Activated output (A):
[[1.00000000e+000 1.00000000e+000 1.00000000e+000 1.00000000e+000
  1.00000000e+000 1.00000000e+000 1.00000000e+000 1.00000000e+000
  1.00000000e+000 1.00000000e+000 1.00000000e+000 1.00000000e+000
  1.00000000e+000 1.00000000e+000 1.00000000e+000 1.00000000e+000
  1.00000000e+000 1.00000000e+000 1.00000000e+000 1.00000000e+000
  1.00000000e+000 1.00000000e+000 1.00000000e+000 1.00000000e+000
  1.00000000e+000 1.00000000e+000 1.00000000e+000 1.00000000e+000
  1.00000000e+000 1.00000000e+000 1.00000000e+000 1.00000000e+000
  1.00000000e+000 1.00000000e+000 1.00000000e+000 1.00000000e+000
  1.00000000e+000 1.00000000e+000 1.00000000e+000 1.00000000e+000
  1.00000000e+000 1.00000000e+000 1.00000000e+000 1.00000000e+000
  1.00000000e+000 1.00000000e+000 1.00000000e+000 1.00000000e+000
  1.00000000e+000 1.00000000e+000 1.00000000e+000 1.00000000e+000
  1.00000000e+000 1.00000000e+000 1.00000000e+000 1.00000000e+000
  1.00000000e+000 1.00000000e+000 1.00000000e+000 1.00

<ipython-input-77-ebda66bbab66>:14: RuntimeWarning: overflow encountered in exp
  self.A = 1 / (1 + np.exp(-z))
